# Generated by Django 5.1.2 on 2024-10-14 23:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=16, validators=[authentication.models.validate_age]),
        ),
    ]
