# Generated by Django 5.1.2 on 2024-10-14 23:58

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_birth_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[authentication.models.validate_age]),
        ),
    ]
